name: 'Build LaTex Document'

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #Checks-out the repository
      - name: Checkout
        uses: actions/checkout@v3
      
        # Setup python
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      # Run tectonic to compile document
      - name: Run builder
        run: python3 build_dataframe.py
      
      # Commit dataset
      - name: Add dataset to commit
        run: |
          git add sncf_dataset.csv
          git commit -m "[AUTO] Autobuild dataset with Github Action"
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}